server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:usuariosdb
    driver-class-name: org.h2.Driver
    username: ey
    password: ey
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: "mysecretkey1234567890mysecretkey1234567890"
  expiration: 3600000  # 1 hora en milisegundos
